name: local_pcangsd
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python = 3.9
  - numpy
  - pandas
  - zarr
  - xarray
  - dask
  - scikit-learn < 1.1.0
  - cyvcf2
  - sgkit >= 0.5.0
  - cython
  - scipy
  - scikit-bio
  - matplotlib
  - seaborn
  - ipykernel
  - pip
  - jax
  - pip:
    - git+https://github.com/Rosemeis/pcangsd.git
    - git+https://github.com/jguhlin/lostruct-py.git
