name: local_pcangsd
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python>=3.9
  - numpy
  - pandas
  - zarr
  - xarray
  - dask
  - sgkit>=0.5.0
  - pip
  - cython
  - scipy
  - scikit-bio
  - matplotlib
  - rpy2
  - r-base
  - ipykernel
  - pip:
      - git+https://github.com/Rosemeis/pcangsd.git
      - lostruct
